# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rick Yang
tagline:          'The personal website'
description:      'Base theme for Jekyll themes by @mdo.'
url:              semiexpert.github.io

author:
  name:           'Rick Yang'
  url:            https://twitter.com/semiexpert

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/semiexpert/project

# This is the list of pages to incldue in the header of the website.
pages_list:       ['About', 'Archive']